<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Blog.Application\Blog.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Blog.Infrastructure\Blog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
