<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.1" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Blog.Application\Blog.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Blog.Infrastructure\Blog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Contracts">
      <HintPath>..\..\..\..\..\Contracts\src\Contracts\Contracts\bin\Debug\net10.0\Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
